### ISSUE TITLE
Build failed due to isc library

### ISSUE THREAD

**Issue by foxhoundsk** [bconry/mutrace#2]
Hi, I was building mutrace on Ubuntu 18.04 (amd64).

During using `make` to build mutrace, I encountered an compiler error:
```
make  all-am
make[1]: Entering directory '/home/dces4212/tool/mutrace'
  CC       libmutrace_la-mutrace.lo
mutrace.c:48:10: fatal error: isc/types.h: No such file or directory
 #include <isc/types.h>
          ^~~~~~~~~~~~~
compilation terminated.
```

Should I install the isc library myself? Or there exists tool or option in the source?

If I should install the lib myself, is there any recommended method to install it? Since I only found the lib comes with BIND 9.

Thanks!

**Comment by foxhoundsk** [comment]
Sorry for bothering, I just accidentally compiled mutrace with make command `make mutrace`, seems is my lacking of observation in the makefile.

But I'm still wondering what will be built with default `make` target.

Thanks!

**Comment by foxhoundsk** [comment]
Seems I was misunderstood with command `$ make mutrace`, it just generated script which is entry point to do profiling, the library is still missing to build the dynamic library which mutrace needed.

Any recommendation would be appreciated!

Thanks!

**Comment by foxhoundsk** [comment]
Further update:

I've completed the installation (isc library are installed through using command `make install` in source of BIND9).

But mutrace printed the following error when I'm trying to profile an executable:
```
bash: mutrace.c:510: load_functions: Assertion `real_isc_rwlock_init' failed. 
[1]    10383 abort (core dumped)  LD_PRELOAD=/usr/local/lib/libmutrace.so ./mutrace ../a.out
```

Does this means that I didn't have isc library installed properly?

Thanks!

**Comment by bconry** [comment]
This has been a very low priority side project for me and I'm afraid it's been neglected for a long time.  I haven't completed the integration and testing of my fork of mutrace.  I haven't even tested it with any BIND versions after 9.11.

In other words, I'm not surprised that you've had issues, and I'm sorry that you've come across this project in this state.

For the moment, I think you're probably better off using one of the other mutrace forks.

Brian

**Comment by foxhoundsk** [comment]
Ok, I'll looking for other forks.

Thanks for the response.
